/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UpdateUserRequest } from '../../models/update-user-request';
import { UserResponse } from '../../models/user-response';

export interface ApiUsersUserGuidPut$Plain$Params {

/**
 * Идентификатор пользователя
 */
  userGuid: string;
  
    /**
     * Модель для обновления данных о пользователе
     */
    body?: UpdateUserRequest
}

export function apiUsersUserGuidPut$Plain(http: HttpClient, rootUrl: string, params: ApiUsersUserGuidPut$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<UserResponse>> {
  const rb = new RequestBuilder(rootUrl, apiUsersUserGuidPut$Plain.PATH, 'put');
  if (params) {
    rb.path('userGuid', params.userGuid, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UserResponse>;
    })
  );
}

apiUsersUserGuidPut$Plain.PATH = '/api/Users/{userGuid}';
