/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface IssuedTokenResponse {

  /**
   * Токен доступа пользователя
   */
  accessToken: string;

  /**
   * Токен обновления токена доступа пользователя
   */
  refreshToken: string;
}
