/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SignInRequest {

  /**
   * Эл. почта пользователя
   */
  email: string;

  /**
   * Пароль пользователя
   */
  password: string;
}
