/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Roles } from '../models/roles';
export interface SignUpRequest {

  /**
   * День рождения пользователя
   */
  dateOfBirth: string;

  /**
   * Эл. почта пользователя
   */
  email: string;

  /**
   * Полное имя пользователя
   */
  fullName: string;

  /**
   * Пароль пользователя
   */
  password: string;

  /**
   * Роль пользователя
   */
  roleCode: Roles;
}
