/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Roles } from '../models/roles';
export interface UserResponse {

  /**
   * День рождения пользователя
   */
  dateOfBirth: string;

  /**
   * Эл. почта пользователя
   */
  email: string;

  /**
   * Полное имя пользователя
   */
  fullName: string;

  /**
   * Роль пользователя
   */
  roleCode: Roles;

  /**
   * Идентификатор пользователя
   */
  userGuid: string;
}
