/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface ApiAuthIsValidTokenGet$Json$Params {

/**
 * Токен доступа
 */
  accessToken: string;
}

export function apiAuthIsValidTokenGet$Json(http: HttpClient, rootUrl: string, params: ApiAuthIsValidTokenGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<boolean>> {
  const rb = new RequestBuilder(rootUrl, apiAuthIsValidTokenGet$Json.PATH, 'get');
  if (params) {
    rb.query('accessToken', params.accessToken, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: String((r as HttpResponse<any>).body) === 'true' }) as StrictHttpResponse<boolean>;
    })
  );
}

apiAuthIsValidTokenGet$Json.PATH = '/api/Auth/IsValidToken';
